### ISSUE TITLE
404 message File not Found after Pokemon Go API updated

### ISSUE THREAD

**Issue by ThunderTrent** [OpenPoGo/OpenPoGoWeb#176] opened 2016-08-07 06:25 UTC
I replaced my username with "user" -- It appears that the User..json being passed for map objects hasn't updated to match the api changes -- that or a different internal error.

> :/Projects/pokemonapi/PokemonGo-Bot/web$ python -m SimpleHTTPServer 5901
> Serving HTTP on 0.0.0.0 port 5901 ...
> 127.0.0.1 - - [07/Aug/2016 01:19:52] code 404, message File not found
> 127.0.0.1 - - [07/Aug/2016 01:19:52] "GET /location-user.json?v=1470550792068 HTTP/1.1" 404 -
> 127.0.0.1 - - [07/Aug/2016 01:19:52] code 404, message File not found
> 127.0.0.1 - - [07/Aug/2016 01:19:52] "GET /inventory-user.json?v=1470550792068 HTTP/1.1" 404 -
> 127.0.0.1 - - [07/Aug/2016 01:19:52] code 404, message File not found
> 127.0.0.1 - - [07/Aug/2016 01:19:52] "GET /catchable-user.json?v=1470550792069 HTTP/1.1" 404 -
> 127.0.0.1 - - [07/Aug/2016 01:19:53] code 404, message File not found
> 127.0.0.1 - - [07/Aug/2016 01:19:53] "GET /socket.io/?EIO=3&transport=polling&t=LPZg5jh HTTP/1.1" 404 -
> 127.0.0.1 - - [07/Aug/2016 01:19:53] code 404, message File not found
> 127.0.0.1 - - [07/Aug/2016 01:19:53] "GET /location-user.json?v=1470550793067 HTTP/1.1" 404 -
> 127.0.0.1 - - [07/Aug/2016 01:19:53] code 404, message File not found
> 127.0.0.1 - - [07/Aug/2016 01:19:53] "GET /catchable-user.json?v=1470550793068 HTTP/1.1" 404 -
> 127.0.0.1 - - [07/Aug/2016 01:19:53] code 404, message File not found
> 127.0.0.1 - - [07/Aug/2016 01:19:53] "GET /location-user.json?v=1470550793481 HTTP/1.1" 404 -
> 127.0.0.1 - - [07/Aug/2016 01:19:53] code 404, message File not found
> 127.0.0.1 - - [07/Aug/2016 01:19:53] "GET /catchable-user.json?v=1470550793481 HTTP/1.1" 404 -
> 127.0.0.1 - - [07/Aug/2016 01:19:54] "GET / HTTP/1.1" 200 -
> 127.0.0.1 - - [07/Aug/2016 01:19:54] "GET /css/main.css HTTP/1.1" 200 -
> 127.0.0.1 - - [07/Aug/2016 01:19:54] "GET /config/userdata.js HTTP/1.1" 200 -

**Comment by SingularityIO** [comment] 2016-08-07 06:34
Also receiving this same error, which causes the Pokemon/Stops/Nodes/Players to stop spawning on the Map/markers

`XMLHttpRequest {readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, responseURL: "http://localhost:8000/inventory-REMOVED.json?v=1470551590794"…}errorFunc @ main.js:520xhr.onreadystatechange @ main.js:978
http://localhost:8000/inventory-REMOVED.json?v=1470551590823 Failed to load resource: the server responded with a status of 404 (File not found)
main.js:520 XMLHttpRequest {readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, responseURL: "http://localhost:8000/inventory-REMOVED.json?v=1470551590823"…}`

`XMLHttpRequest {readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, responseURL: "http://localhost:8000/location-REMOVED.json?v=1470551591217"…}errorFunc @ main.js:520xhr.onreadystatechange @ main.js:978
20main.js:194 Uncaught TypeError: Cannot read property 'setOptions' of undefinedsetBotPathOptions @ main.js:194trainerFunc @ main.js:951xhr.onreadystatechange @ main.js:975
VM119:1 Uncaught SyntaxError: Unexpected end of JSON inputxhr.onreadystatechange @ main.js:975
VM120:1 Uncaught SyntaxError: Unexpected end of JSON inputxhr.onreadystatechange @ main.js:975
VM121:1 Uncaught SyntaxError: Unexpected end of JSON inputxhr.onreadystatechange @ main.js:975
VM122:1 Uncaught SyntaxError: Unexpected end of JSON inputxhr.onreadystatechange @ main.js:975
VM123:1 Uncaught SyntaxError: Unexpected end of JSON inputxhr.onreadystatechange @ main.js:975
VM124:1 Uncaught SyntaxError: Unexpected end of JSON inputxhr.onreadystatechange @ main.js:975
VM125:1 Uncaught SyntaxError: Unexpected end of JSON inputxhr.onreadystatechange @ main.js:975
VM126:1 Uncaught SyntaxError: Unexpected end of JSON inputxhr.onreadystatechange @ main.js:975
VM127:1 Uncaught SyntaxError: Unexpected end of JSON inputxhr.onreadystatechange @ main.js:975
VM128:1 Uncaught SyntaxError: Unexpected end of JSON inputxhr.onreadystatechange @ main.js:975
VM129:1 Uncaught SyntaxError: Unexpected end of JSON inputxhr.onreadystatechange @ main.js:975
VM130:1 Uncaught SyntaxError: Unexpected end of JSON inputxhr.onreadystatechange @ main.js:975
VM131:1 Uncaught SyntaxError: Unexpected end of JSON inputxhr.onreadystatechange @ main.js:975
VM132:1 Uncaught SyntaxError: Unexpected end of JSON inputxhr.onreadystatechange @ main.js:975
VM133:1 Uncaught SyntaxError: Unexpected end of JSON inputxhr.onreadystatechange @ main.js:975
VM134:1 Uncaught SyntaxError: Unexpected end of JSON inputxhr.onreadystatechange @ main.js:975
VM135:1 Uncaught SyntaxError: Unexpected end of JSON inputxhr.onreadystatechange @ main.js:975
VM136:1 Uncaught SyntaxError: Unexpected end of JSON inputxhr.onreadystatechange @ main.js:975
VM137:1 Uncaught SyntaxError: Unexpected end of JSON inputxhr.onreadystatechange @ main.js:975
VM138:1 Uncaught SyntaxError: Unexpected end of JSON inputxhr.onreadystatechange @ main.js:975
VM139:1 Uncaught SyntaxError: Unexpected end of JSON inputxhr.onreadystatechange @ main.js:975
VM140:1 Uncaught SyntaxError: Unexpected end of JSON input`

Removed multiple users from userdata.js down to 1 and it works, but having multiple just seems to screw it over big time.

**Comment by ThunderTrent** [comment] 2016-08-07 06:46
I found out the initial error was due to config -- I digged into how the application was serving the json files and realized the username is the email address if Google. Might want to add that in instructions to clear up confusion. Seems to be working now -- I will post if I end up getting any more json errors.

**Comment by ThunderTrent** [comment] 2016-08-07 06:48
Well, yeah. catchable.json isn't being generated -- Going to dig and see if I can find out at what point it breaks.

**Comment by anrchy420** [comment] 2016-08-07 06:59
also getting the catchable.json isn't being generated please let me know if you found resolve.

**Comment by wchill** [comment] 2016-08-07 07:28
Duplicate of #175.

**Closed as completed by wchill** 2016-08-07 07:28 UTC
